### ISSUE TITLE
single vs. double asterisks

### ISSUE THREAD

**Issue by razor-1** [hairyhenderson/go-codeowners#2]
At https://github.com/hairyhenderson/go-codeowners/blob/master/codeowners.go#L103 an equivalence is put in place for `*` and `**`, and the comment indicates that the codeowners rules differ from gitignore. However, at https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax it states that the syntax is the same, and the example specifically states that a `*` only matches the directory, not recursively matching its children.

**Comment by hairyhenderson** [comment]
Hi @razor-1, thanks for logging this, and sorry for the slow response!

It's been almost 2 years since I've touched this code, and I think the original use-case I had for it fizzled out (I can't even remember why I wrote this 😂)... That being said, I _vaguely_ remember the GitHub docs at the time stating otherwise at the time. May have been a misunderstanding on my part, but the GitHub docs have also been totally revamped since then.

Actually, reading a little closer, the special case is right there on the first line in their example:

```
# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
# @global-owner1 and @global-owner2 will be requested for
# review when someone opens a pull request.
*       @global-owner1 @global-owner2
```

Key phrase there is _"everything in the repo"_. I think the key is that this refers to _just_ `*`, rather than `<dir>/*`.

Actually `git` behaves the same way (kindof?) with `.gitignore` - a single `*` causes the entire repo to be matched:

```console
$ tree -a
.
├── .git
[...]
├── .gitignore
├── a
│   ├── aa
│   │   └── file
│   └── file
├── b
│   └── file
├── c
│   └── file
└── file

13 directories, 22 files
$ cat .gitignore
*
$ git status -sb
## No commits yet on master
```

Let me know if that makes sense!

**Comment by razor-1** [comment]
thanks, it does - but perhaps the lone `*` is a special case, because dir/* and dir/** should definitely refer to different things (and do, based on how github processes codeowners) but currently that behavior isn't reflected in this implementation.

**Comment by hairyhenderson** [comment]
Ah, ok. Thanks for clarifying!

The line of code you linked to _only_ handles the `*` special-case. I'm using a `.gitignore`-parsing package under the covers (https://github.com/sabhiram/go-gitignore), so  there may be a different behaviour there.

I think the GitHub docs are contradictory, too: they claim that they follow the `.gitignore` format, but in `.gitignore`, `dir/*` _will_ actually match `dir/subdir/file`:

```console
$ cat .gitignore
a/*
$ git check-ignore --no-index -v a/aa/file
.gitignore:1:a/*	a/aa/file
```

(translation: `git` thinks `a/aa/file` _should_ be ignored)

So it seems I'll need to handle this particular case differently and deviate from the subpackage I'm using.

**Comment by hairyhenderson** [comment]
So, looking at this a bit more closely, and starting to write a few unit tests around https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax, I'm realizing that my implementation has _a lot_ of errors. 🤦‍♂

Thank you for alerting me to this, @razor-1 - I've got some failing tests now, and so it shouldn't take more than a few days (hopefully!) to get things working again! 😅

**Comment by hairyhenderson** [comment]
@razor-1 hopefully #6 fixes it. I've tagged it as `v0.2.0` too.

Let me know if things are working more correctly for you!

**Comment by razor-1** [comment]
Yep looking great now! Thank you much for the speedy response!
